[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 9600
monitor_filters = esp32_exception_decoder

; Configuration USB
upload_speed = 460800
upload_protocol = esptool

; Librairies requises
lib_deps = 
    NimBLE-Arduino@^2.5.1
    dfrobot/DFRobot_BloodOxygen_S@^1.0.0
    dfrobot/DFRobot_RTU@^1.0.6
    https://github.com/electroniccats/mpu6050.git
    ArduinoJson@^7.4.3

; Flags de compilation
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -std=c++17

; Configuration mémoire
board_build.partitions = default.csv